using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.UI.Dispatching;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Media;
using PigeonPost.Models;
using PigeonPost.Services;
using MUC = Microsoft.UI.Colors;
using Windows.UI;

namespace PigeonPost.ViewModels;

/// <summary>
/// Primary ViewModel for <c>MainWindow</c>.
/// Exposes observable properties and relay commands consumed by the XAML bindings.
/// All UI-visible state changes are marshalled to the UI thread via <see cref="_ui"/>.
/// </summary>
public partial class MainViewModel : ObservableObject
{
    /// <summary>Maximum number of log entries kept in <see cref="LogEntries"/> before older ones are discarded.</summary>
    private const int LogCap = 500;

    private readonly AppState _state;
    private readonly DispatcherQueue _ui;
    private readonly DispatcherQueueTimer _uptimeTimer;

    /// <summary>
    /// The hosting <see cref="Window"/>, set by <c>MainWindow</c> after construction.
    /// Used by the Hide/Show commands to show and hide the AppWindow.
    /// </summary>
    public Window? HostWindow { get; set; }

    /// <summary>Live-updating collection of log entries; bound to the activity-log ListView.</summary>
    public ObservableCollection<LogEntry> LogEntries { get; } = new();

    /// <summary>Static caption shown below the listening address (evaluated once at startup).</summary>
    public string DownloadsLine { get; }

    // ---- Observable properties (source-generated by CommunityToolkit.Mvvm) ----
    // MVVMTK0045 suppressed: partial-property AOT pattern is not compatible with
    // the Windows App SDK 2.0 XAML compiler pipeline when building without Visual Studio.
    // Field-based [ObservableProperty] is fully functional for this unpackaged desktop app.
#pragma warning disable MVVMTK0045
    [ObservableProperty] private string _statusText   = "Running";
    [ObservableProperty] private Brush  _statusBrush  = new SolidColorBrush(MUC.SeaGreen);

    /// <summary>Colour forwarded to <c>MainWindow</c> so it can redraw the tray icon.</summary>
    [ObservableProperty] private Color  _trayIconColor = MUC.SeaGreen;

    [ObservableProperty] private string _pauseButtonText = "Pause";
    [ObservableProperty] private bool   _isPaused;

    [ObservableProperty] private int    _filesReceived;
    [ObservableProperty] private int    _clipboardSends;
    [ObservableProperty] private int    _clipboardReceives;
    [ObservableProperty] private string _uptimeText   = "00:00:00";

    /// <summary>Formatted address shown in the address card (e.g. "http://192.168.1.5:2560").</summary>
    [ObservableProperty] private string _listenAddress = "";

    /// <summary>Live count of log entries shown as a badge on the Activity log header.</summary>
    [ObservableProperty] private string _logCount = "0";

    /// <summary>Collapses the badge when there are no entries (avoids showing "0").</summary>
    [ObservableProperty] private Microsoft.UI.Xaml.Visibility _logCountVisible =
        Microsoft.UI.Xaml.Visibility.Collapsed;
#pragma warning restore MVVMTK0045

    public MainViewModel(AppState state, DispatcherQueue ui)
    {
        _state = state;
        _ui    = ui;

        ListenAddress = $"http://{NetworkHelper.GetPrimaryLocalIp()}:{Constants.Port}";
        DownloadsLine = $"Files saved to:  {Constants.DownloadsFolder}";

        // Subscribe to events raised by the background HTTP listener thread.
        _state.LogEntryAdded   += OnLogEntry;
        _state.CountersChanged += OnCountersChanged;

        // Tick every second to keep the uptime display current.
        _uptimeTimer          = _ui.CreateTimer();
        _uptimeTimer.Interval = TimeSpan.FromSeconds(1);
        _uptimeTimer.Tick    += (_, _) => UpdateUptime();
        _uptimeTimer.Start();
    }

    // ---------------------------------------------------------------- event handlers

    /// <summary>
    /// Invoked on a background thread when a new log entry arrives.
    /// Marshals to the UI thread and caps the collection at <see cref="LogCap"/>.
    /// </summary>
    private void OnLogEntry(LogEntry entry)
    {
        _ui.TryEnqueue(() =>
        {
            LogEntries.Add(entry);
            // Remove oldest entries to prevent unbounded memory growth.
            while (LogEntries.Count > LogCap)
                LogEntries.RemoveAt(0);
            UpdateLogBadge();
        });
    }

    /// <summary>
    /// Invoked on a background thread when any counter changes.
    /// Copies the latest values to the observable properties on the UI thread.
    /// </summary>
    private void OnCountersChanged()
    {
        _ui.TryEnqueue(() =>
        {
            FilesReceived     = _state.FilesReceived;
            ClipboardSends    = _state.ClipboardSends;
            ClipboardReceives = _state.ClipboardReceives;
        });
    }

    /// <summary>Recalculates and formats the elapsed uptime string. Called every second.</summary>
    private void UpdateUptime()
    {
        var d = DateTimeOffset.Now - _state.StartedAt;
        UptimeText = $"{(int)d.TotalHours:D2}:{d.Minutes:D2}:{d.Seconds:D2}";
    }

    /// <summary>
    /// Updates <see cref="StatusBrush"/> and <see cref="TrayIconColor"/> to the
    /// theme-appropriate colour for the current running/paused state.
    /// Looks up named brushes from <c>Application.Current.Resources</c> which returns
    /// the Light or Dark variant depending on the active Windows theme.
    /// Must be called on the UI thread.
    /// </summary>
    public void RefreshStatusColors()
    {
        var key       = _state.Paused ? "StatusPausedBrush" : "StatusRunningBrush";
        var resources = Application.Current.Resources;

        if (resources.TryGetValue(key, out var brushObj) && brushObj is SolidColorBrush scb)
        {
            StatusBrush   = scb;
            TrayIconColor = scb.Color;
        }
    }

    // -------------------------------------------------------------- commands

    /// <summary>Toggles the paused state and updates all related visual indicators.</summary>
    [RelayCommand]
    private void TogglePause()
    {
        _state.Paused = !_state.Paused;
        IsPaused      = _state.Paused;

        if (_state.Paused)
        {
            StatusText      = "Paused";
            PauseButtonText = "Resume";
            _state.Emit(LogLevel.Warn, "Server paused — incoming requests will be rejected");
        }
        else
        {
            StatusText      = "Running";
            PauseButtonText = "Pause";
            _state.Emit(LogLevel.Success, "Server resumed");
        }

        // Re-resolve colour from the active theme dictionary (light or dark).
        RefreshStatusColors();
    }

    /// <summary>Opens the Downloads folder in Windows Explorer.</summary>
    [RelayCommand]
    private void OpenDownloads()
    {
        try
        {
            Process.Start(new ProcessStartInfo
            {
                FileName       = Constants.DownloadsFolder,
                UseShellExecute = true,
            });
        }
        catch (Exception ex)
        {
            _state.Emit(LogLevel.Error, $"Could not open Downloads: {ex.Message}");
        }
    }

    /// <summary>Hides the main window; the app continues running in the system tray.</summary>
    [RelayCommand]
    private void HideToTray()
    {
        try { HostWindow?.AppWindow?.Hide(); } catch { /* AppWindow unavailable in some hosts */ }
    }

    /// <summary>Restores and activates the main window (called from the tray icon menu).</summary>
    [RelayCommand]
    private void ShowWindow()
    {
        try
        {
            HostWindow?.AppWindow?.Show();
            HostWindow?.Activate();
        }
        catch { /* ignored */ }
    }

    /// <summary>Clears all entries from the activity log.</summary>
    [RelayCommand]
    private void ClearLog()
    {
        LogEntries.Clear();
        UpdateLogBadge();
    }

    /// <summary>Refreshes the log-count badge text and visibility.</summary>
    private void UpdateLogBadge()
    {
        LogCount        = LogEntries.Count.ToString();
        LogCountVisible = LogEntries.Count > 0
            ? Microsoft.UI.Xaml.Visibility.Visible
            : Microsoft.UI.Xaml.Visibility.Collapsed;
    }

    /// <summary>
    /// Exits the application. The caller is responsible for disposing the tray icon
    /// before invoking this command (see <c>MainWindow.BuildTrayMenu</c>).
    /// </summary>
    [RelayCommand]
    private void Quit() => Application.Current.Exit();
}